// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbV2PzKywj54eSdox5kQtrnIRAT7qr8Z4',
    appId: '1:726104051748:web:1e4fff3999bf07484e08b1',
    messagingSenderId: '726104051748',
    projectId: 'socialevote',
    authDomain: 'socialevote.firebaseapp.com',
    storageBucket: 'socialevote.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHUCDMUc7GJlcwbLgqJeG0Sn5q6bovIC4',
    appId: '1:726104051748:android:ad6a99e4419631fd4e08b1',
    messagingSenderId: '726104051748',
    projectId: 'socialevote',
    storageBucket: 'socialevote.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyk3JrHwt7AEOrcp7G4yU5km_2ycrJs-E',
    appId: '1:726104051748:ios:bb7ced079814c2ea4e08b1',
    messagingSenderId: '726104051748',
    projectId: 'socialevote',
    storageBucket: 'socialevote.firebasestorage.app',
    iosBundleId: 'com.example.socialeVote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyk3JrHwt7AEOrcp7G4yU5km_2ycrJs-E',
    appId: '1:726104051748:ios:bb7ced079814c2ea4e08b1',
    messagingSenderId: '726104051748',
    projectId: 'socialevote',
    storageBucket: 'socialevote.firebasestorage.app',
    iosBundleId: 'com.example.socialeVote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbV2PzKywj54eSdox5kQtrnIRAT7qr8Z4',
    appId: '1:726104051748:web:c1da5c5aa434ddf64e08b1',
    messagingSenderId: '726104051748',
    projectId: 'socialevote',
    authDomain: 'socialevote.firebaseapp.com',
    storageBucket: 'socialevote.firebasestorage.app',
  );

}