import 'package:flutter/widgets.dart';

import 'package:sociale_vote/app/localization/de_fallback.dart';

enum WorkspaceUiTerm {
  sessions,
  session,
  team,
  organization,
  business,
  businessWorkspace,
}

String workspaceUiTermForLanguageCode(
  String languageCode,
  WorkspaceUiTerm term,
) {
  final language = languageCode.trim().toLowerCase();
  final values = _workspaceTerms[language] ?? _workspaceTerms['en']!;
  return values[term.index];
}

String workspaceUiTerm(BuildContext context, WorkspaceUiTerm term) {
  return workspaceUiTermForLanguageCode(
    Localizations.localeOf(context).languageCode,
    term,
  );
}

String? workspaceLocalizedOverrideForLanguageCode(
  String languageCode,
  String english,
) {
  final language = languageCode.trim().toLowerCase();
  return _workspaceOverrides[language]?[english];
}

String workspaceTr(
  BuildContext context, {
  required String italian,
  required String english,
  required String german,
}) {
  final language = Localizations.localeOf(context).languageCode.toLowerCase();
  if (language == 'it') return italian;
  if (language == 'de') return german;
  final localizedOverride =
      workspaceLocalizedOverrideForLanguageCode(language, english);
  if (localizedOverride != null) return localizedOverride;
  return deOrEnglish(context, english: english, german: german);
}

const Map<String, List<String>> _workspaceTerms = <String, List<String>>{
  'en': <String>[
    'Sessions',
    'Session',
    'Team',
    'Organization',
    'Business',
    'Organization workspace',
  ],
  'it': <String>[
    'Sessioni',
    'Sessione',
    'Gruppo',
    'Organizzazione',
    'Professionale',
    'Spazio di lavoro organizzativo',
  ],
  'de': <String>[
    'Sitzungen',
    'Sitzung',
    'Team',
    'Organisation',
    'Geschäftlich',
    'Organisations-Arbeitsbereich',
  ],
  'fa': <String>[
    'جلسه‌ها',
    'جلسه',
    'تیم',
    'سازمان',
    'کسب‌وکار',
    'فضای کاری سازمانی',
  ],
  'es': <String>[
    'Sesiones',
    'Sesión',
    'Equipo',
    'Organización',
    'Empresarial',
    'Espacio de trabajo de la organización',
  ],
  'pt': <String>[
    'Sessões',
    'Sessão',
    'Equipe',
    'Organização',
    'Empresarial',
    'Espaço de trabalho da organização',
  ],
  'fr': <String>[
    'Sessions',
    'Session',
    'Équipe',
    'Organisation',
    'Professionnel',
    'Espace de travail de l’organisation',
  ],
  'ar': <String>[
    'الجلسات',
    'جلسة',
    'الفريق',
    'المنظمة',
    'الأعمال',
    'مساحة عمل المنظمة',
  ],
  'ro': <String>[
    'Sesiuni',
    'Sesiune',
    'Echipă',
    'Organizație',
    'Profesional',
    'Spațiul de lucru al organizației',
  ],
  'ru': <String>[
    'Сессии',
    'Сессия',
    'Команда',
    'Организация',
    'Бизнес',
    'Рабочее пространство организации',
  ],
  'zh': <String>[
    '会议',
    '会议',
    '团队',
    '组织',
    '商务',
    '组织工作区',
  ],
};

const Map<String, Map<String, String>> _workspaceOverrides =
    <String, Map<String, String>>{
  'fa': <String, String>{
    'Business Pilot': 'دوره آزمایشی کسب‌وکار',
    'Official publishing, live consultations and verifiable results in one workspace.': 'انتشار رسمی، مشورت‌های زنده و نتایج قابل‌راستی‌آزمایی در یک فضای کاری.',
    'Live sessions': 'جلسه‌های زنده',
    'Verified Results': 'نتایج تأییدشده',
    'No sessions yet': 'هنوز جلسه‌ای وجود ندارد',
    'Create a session to start collecting participation and results.': 'برای شروع جمع‌آوری مشارکت و نتایج، یک جلسه ایجاد کنید.',
    'Voce to communicate, Vote to consult, Session for live participation and verifiable results.': 'Voce برای ارتباط، Vote برای مشورت و جلسه برای مشارکت زنده و نتایج قابل‌راستی‌آزمایی.',
    'Manage access, QR, questions, stage, participation and session closure.': 'دسترسی، QR، پرسش‌ها، صحنه، مشارکت و بستن جلسه را مدیریت کنید.',
    'New session': 'جلسه جدید',
    'No sessions': 'بدون جلسه',
    'Sessions created by the organization will appear here.': 'جلسه‌های ایجادشده توسط سازمان اینجا نمایش داده می‌شوند.',
    'No Verified Results yet': 'هنوز نتیجه تأییدشده‌ای وجود ندارد',
    'When a session closes with a verified report, the result will appear here.': 'وقتی یک جلسه با گزارش تأییدشده بسته شود، نتیجه اینجا نمایش داده می‌شود.',
    'Operate sessions': 'مدیریت جلسه‌ها',
    'Team and roles': 'تیم و نقش‌ها',
    'Team unavailable': 'تیم در دسترس نیست',
    'This version manages already registered Social Vote accounts. External email invitations, link acceptance and Owner transfer remain unavailable until that workflow is complete.': 'این نسخه حساب‌های ثبت‌شده Social Vote را مدیریت می‌کند. دعوت ایمیلی خارجی، پذیرش از طریق پیوند و انتقال مالکیت تا تکمیل این فرایند در دسترس نیست.',
    'Official organization data powers the public signature, workspace and Business services.': 'داده‌های رسمی سازمان، امضای عمومی، فضای کاری و خدمات کسب‌وکار را پشتیبانی می‌کنند.',
    'Workspace operational': 'فضای کاری عملیاتی',
    'Workspace restricted': 'فضای کاری محدود',
    'Organization verified and workspace active. Actions remain subject to backend/RLS enforcement.': 'سازمان تأیید شده و فضای کاری فعال است. اقدام‌ها همچنان تابع قواعد backend/RLS هستند.',
    'Business services remain limited until identity and workspace satisfy server-side requirements.': 'خدمات کسب‌وکار تا زمانی که هویت و فضای کاری الزامات سمت سرور را برآورده نکنند محدود می‌مانند.',
    'Organization identity, roles, workspace status and permissions are verified server-side. The pilot does not sell verification, ranking or visibility. Verified Results remain separate from ordinary publishing.': 'هویت سازمان، نقش‌ها، وضعیت فضای کاری و مجوزها در سمت سرور بررسی می‌شوند. دوره آزمایشی تأیید، رتبه‌بندی یا دیده‌شدن را نمی‌فروشد. نتایج تأییدشده از انتشار عادی جدا می‌مانند.',
    'Run a consultation with QR, Stage, access control and Verified Result.': 'یک مشورت با QR، صحنه، کنترل دسترسی و نتیجه تأییدشده اجرا کنید.',
    'QR, Stage and Verified Result.': 'QR، صحنه و نتیجه تأییدشده.',
    'Create Session': 'ایجاد جلسه',
    'Workspace not active': 'فضای کاری فعال نیست',
    'Workspace Pilot': 'فضای کاری آزمایشی',
    'Workspace active': 'فضای کاری فعال',
    'Workspace suspended': 'فضای کاری تعلیق‌شده',
    'Workspace expired': 'فضای کاری منقضی‌شده',
    'Owner': 'مالک',
    'Manager': 'مدیر',
    'Operator': 'اپراتور',
    'Viewer': 'مشاهده‌گر',
  },
  'es': <String, String>{
    'Business Pilot': 'Piloto empresarial',
    'Official publishing, live consultations and verifiable results in one workspace.': 'Publicación oficial, consultas en vivo y resultados verificables en un solo espacio de trabajo.',
    'Live sessions': 'Sesiones en vivo',
    'Verified Results': 'Resultados verificados',
    'No sessions yet': 'Aún no hay sesiones',
    'Create a session to start collecting participation and results.': 'Crea una sesión para empezar a recopilar participación y resultados.',
    'Voce to communicate, Vote to consult, Session for live participation and verifiable results.': 'Voce para comunicar, Vote para consultar y una sesión para la participación en vivo y los resultados verificables.',
    'Manage access, QR, questions, stage, participation and session closure.': 'Gestiona el acceso, QR, las preguntas, el escenario, la participación y el cierre de la sesión.',
    'New session': 'Nueva sesión',
    'No sessions': 'Sin sesiones',
    'Sessions created by the organization will appear here.': 'Las sesiones creadas por la organización aparecerán aquí.',
    'No Verified Results yet': 'Aún no hay resultados verificados',
    'When a session closes with a verified report, the result will appear here.': 'Cuando una sesión se cierre con un informe verificado, el resultado aparecerá aquí.',
    'Operate sessions': 'Gestionar sesiones',
    'Team and roles': 'Equipo y roles',
    'Team unavailable': 'Equipo no disponible',
    'This version manages already registered Social Vote accounts. External email invitations, link acceptance and Owner transfer remain unavailable until that workflow is complete.': 'Esta versión gestiona cuentas de Social Vote ya registradas. Las invitaciones externas por correo, la aceptación mediante enlace y la transferencia de propietario seguirán sin estar disponibles hasta completar ese flujo.',
    'Official organization data powers the public signature, workspace and Business services.': 'Los datos oficiales de la organización alimentan la firma pública, el espacio de trabajo y los servicios empresariales.',
    'Workspace operational': 'Espacio de trabajo operativo',
    'Workspace restricted': 'Espacio de trabajo restringido',
    'Organization verified and workspace active. Actions remain subject to backend/RLS enforcement.': 'Organización verificada y espacio de trabajo activo. Las acciones siguen sujetas a las reglas de backend/RLS.',
    'Business services remain limited until identity and workspace satisfy server-side requirements.': 'Los servicios empresariales siguen limitados hasta que la identidad y el espacio de trabajo cumplan los requisitos del servidor.',
    'Organization identity, roles, workspace status and permissions are verified server-side. The pilot does not sell verification, ranking or visibility. Verified Results remain separate from ordinary publishing.': 'La identidad de la organización, los roles, el estado del espacio de trabajo y los permisos se verifican en el servidor. El piloto no vende verificación, clasificación ni visibilidad. Los resultados verificados permanecen separados de la publicación ordinaria.',
    'Run a consultation with QR, Stage, access control and Verified Result.': 'Realiza una consulta con QR, escenario, control de acceso y resultado verificado.',
    'QR, Stage and Verified Result.': 'QR, escenario y resultado verificado.',
    'Create Session': 'Crear sesión',
    'Workspace not active': 'Espacio de trabajo no activo',
    'Workspace Pilot': 'Espacio de trabajo piloto',
    'Workspace active': 'Espacio de trabajo activo',
    'Workspace suspended': 'Espacio de trabajo suspendido',
    'Workspace expired': 'Espacio de trabajo caducado',
    'Owner': 'Propietario',
    'Manager': 'Responsable',
    'Operator': 'Operador',
    'Viewer': 'Lector',
  },
  'pt': <String, String>{
    'Business Pilot': 'Piloto empresarial',
    'Official publishing, live consultations and verifiable results in one workspace.': 'Publicação oficial, consultas ao vivo e resultados verificáveis em um único espaço de trabalho.',
    'Live sessions': 'Sessões ao vivo',
    'Verified Results': 'Resultados verificados',
    'No sessions yet': 'Ainda não há sessões',
    'Create a session to start collecting participation and results.': 'Crie uma sessão para começar a coletar participação e resultados.',
    'Voce to communicate, Vote to consult, Session for live participation and verifiable results.': 'Voce para comunicar, Vote para consultar e uma sessão para participação ao vivo e resultados verificáveis.',
    'Manage access, QR, questions, stage, participation and session closure.': 'Gerencie o acesso, QR, as perguntas, o palco, a participação e o encerramento da sessão.',
    'New session': 'Nova sessão',
    'No sessions': 'Sem sessões',
    'Sessions created by the organization will appear here.': 'As sessões criadas pela organização aparecerão aqui.',
    'No Verified Results yet': 'Ainda não há resultados verificados',
    'When a session closes with a verified report, the result will appear here.': 'Quando uma sessão for encerrada com um relatório verificado, o resultado aparecerá aqui.',
    'Operate sessions': 'Gerenciar sessões',
    'Team and roles': 'Equipe e funções',
    'Team unavailable': 'Equipe indisponível',
    'This version manages already registered Social Vote accounts. External email invitations, link acceptance and Owner transfer remain unavailable until that workflow is complete.': 'Esta versão gerencia contas do Social Vote já registradas. Convites externos por email, aceitação por link e transferência de proprietário permanecem indisponíveis até que esse fluxo seja concluído.',
    'Official organization data powers the public signature, workspace and Business services.': 'Os dados oficiais da organização alimentam a assinatura pública, o espaço de trabalho e os serviços empresariais.',
    'Workspace operational': 'Espaço de trabalho operacional',
    'Workspace restricted': 'Espaço de trabalho restrito',
    'Organization verified and workspace active. Actions remain subject to backend/RLS enforcement.': 'Organização verificada e espaço de trabalho ativo. As ações continuam sujeitas às regras de backend/RLS.',
    'Business services remain limited until identity and workspace satisfy server-side requirements.': 'Os serviços empresariais permanecem limitados até que a identidade e o espaço de trabalho atendam aos requisitos do servidor.',
    'Organization identity, roles, workspace status and permissions are verified server-side. The pilot does not sell verification, ranking or visibility. Verified Results remain separate from ordinary publishing.': 'A identidade da organização, as funções, o estado do espaço de trabalho e as permissões são verificados no servidor. O piloto não vende verificação, classificação nem visibilidade. Os resultados verificados permanecem separados da publicação comum.',
    'Run a consultation with QR, Stage, access control and Verified Result.': 'Conduza uma consulta com QR, palco, controle de acesso e resultado verificado.',
    'QR, Stage and Verified Result.': 'QR, palco e resultado verificado.',
    'Create Session': 'Criar sessão',
    'Workspace not active': 'Espaço de trabalho inativo',
    'Workspace Pilot': 'Espaço de trabalho piloto',
    'Workspace active': 'Espaço de trabalho ativo',
    'Workspace suspended': 'Espaço de trabalho suspenso',
    'Workspace expired': 'Espaço de trabalho expirado',
    'Owner': 'Proprietário',
    'Manager': 'Gerente',
    'Operator': 'Operador',
    'Viewer': 'Leitor',
  },
  'fr': <String, String>{
    'Roles, additions, changes and revocations are enforced server-side and recorded in the Organization audit.': 'Les rôles, ajouts, modifications et révocations sont appliqués côté serveur et enregistrés dans le journal d’audit de l’organisation.',
    'No active memberships are currently available for this Organization.': 'Aucune adhésion active n’est actuellement disponible pour cette organisation.',
    'Business Pilot': 'Pilote professionnel',
    'Official publishing, live consultations and verifiable results in one workspace.': 'Publication officielle, consultations en direct et résultats vérifiables dans un seul espace de travail.',
    'Live sessions': 'Sessions en direct',
    'Verified Results': 'Résultats vérifiés',
    'No sessions yet': 'Aucune session pour le moment',
    'Create a session to start collecting participation and results.': 'Créez une session pour commencer à recueillir la participation et les résultats.',
    'Voce to communicate, Vote to consult, Session for live participation and verifiable results.': 'Voce pour communiquer, Vote pour consulter et une session pour la participation en direct et les résultats vérifiables.',
    'Manage access, QR, questions, stage, participation and session closure.': 'Gérez l’accès, le QR, les questions, la scène, la participation et la clôture de la session.',
    'New session': 'Nouvelle session',
    'No sessions': 'Aucune session',
    'Sessions created by the organization will appear here.': 'Les sessions créées par l’organisation apparaîtront ici.',
    'No Verified Results yet': 'Aucun résultat vérifié pour le moment',
    'When a session closes with a verified report, the result will appear here.': 'Lorsqu’une session se termine avec un rapport vérifié, le résultat apparaît ici.',
    'Operate sessions': 'Gérer les sessions',
    'Team and roles': 'Équipe et rôles',
    'Team unavailable': 'Équipe indisponible',
    'This version manages already registered Social Vote accounts. External email invitations, link acceptance and Owner transfer remain unavailable until that workflow is complete.': 'Cette version gère les comptes Social Vote déjà enregistrés. Les invitations externes par e-mail, l’acceptation par lien et le transfert de propriétaire restent indisponibles tant que ce flux n’est pas terminé.',
    'Official organization data powers the public signature, workspace and Business services.': 'Les données officielles de l’organisation alimentent la signature publique, l’espace de travail et les services professionnels.',
    'Workspace operational': 'Espace de travail opérationnel',
    'Workspace restricted': 'Espace de travail restreint',
    'Organization verified and workspace active. Actions remain subject to backend/RLS enforcement.': 'Organisation vérifiée et espace de travail actif. Les actions restent soumises aux règles backend/RLS.',
    'Business services remain limited until identity and workspace satisfy server-side requirements.': 'Les services professionnels restent limités tant que l’identité et l’espace de travail ne satisfont pas aux exigences du serveur.',
    'Organization identity, roles, workspace status and permissions are verified server-side. The pilot does not sell verification, ranking or visibility. Verified Results remain separate from ordinary publishing.': 'L’identité de l’organisation, les rôles, le statut de l’espace de travail et les autorisations sont vérifiés côté serveur. Le pilote ne vend ni vérification, ni classement, ni visibilité. Les résultats vérifiés restent séparés de la publication ordinaire.',
    'Run a consultation with QR, Stage, access control and Verified Result.': 'Menez une consultation avec QR, scène, contrôle d’accès et résultat vérifié.',
    'QR, Stage and Verified Result.': 'QR, scène et résultat vérifié.',
    'Create Session': 'Créer une session',
    'Workspace not active': 'Espace de travail inactif',
    'Workspace Pilot': 'Espace de travail pilote',
    'Workspace active': 'Espace de travail actif',
    'Workspace suspended': 'Espace de travail suspendu',
    'Workspace expired': 'Espace de travail expiré',
    'Owner': 'Propriétaire',
    'Manager': 'Responsable',
    'Operator': 'Opérateur',
    'Viewer': 'Lecteur',
  },
  'ar': <String, String>{
    'Roles, additions, changes and revocations are enforced server-side and recorded in the Organization audit.': 'تُفرض الأدوار والإضافات والتغييرات وسحب الصلاحيات على الخادم وتُسجَّل في سجل تدقيق المنظمة.',
    'No active memberships are currently available for this Organization.': 'لا توجد حاليًا عضويات نشطة لهذه المنظمة.',
    'Business Pilot': 'تجربة الأعمال',
    'Official publishing, live consultations and verifiable results in one workspace.': 'نشر رسمي ومشاورات مباشرة ونتائج قابلة للتحقق داخل مساحة عمل واحدة.',
    'Live sessions': 'الجلسات المباشرة',
    'Verified Results': 'النتائج الموثقة',
    'No sessions yet': 'لا توجد جلسات بعد',
    'Create a session to start collecting participation and results.': 'أنشئ جلسة لبدء جمع المشاركة والنتائج.',
    'Voce to communicate, Vote to consult, Session for live participation and verifiable results.': 'Voce للتواصل وVote للاستشارة، والجلسة للمشاركة المباشرة والنتائج القابلة للتحقق.',
    'Manage access, QR, questions, stage, participation and session closure.': 'أدر الوصول وQR والأسئلة والمنصة والمشاركة وإغلاق الجلسة.',
    'New session': 'جلسة جديدة',
    'No sessions': 'لا توجد جلسات',
    'Sessions created by the organization will appear here.': 'ستظهر الجلسات التي تنشئها المنظمة هنا.',
    'No Verified Results yet': 'لا توجد نتائج موثقة بعد',
    'When a session closes with a verified report, the result will appear here.': 'عند إغلاق جلسة بتقرير موثق ستظهر النتيجة هنا.',
    'Operate sessions': 'إدارة الجلسات',
    'Team and roles': 'الفريق والأدوار',
    'Team unavailable': 'الفريق غير متاح',
    'This version manages already registered Social Vote accounts. External email invitations, link acceptance and Owner transfer remain unavailable until that workflow is complete.': 'تدير هذه النسخة حسابات Social Vote المسجلة بالفعل. وتظل دعوات البريد الإلكتروني الخارجية والقبول عبر الرابط ونقل الملكية غير متاحة حتى اكتمال هذا المسار.',
    'Official organization data powers the public signature, workspace and Business services.': 'تغذي بيانات المنظمة الرسمية التوقيع العام ومساحة العمل وخدمات الأعمال.',
    'Workspace operational': 'مساحة العمل جاهزة',
    'Workspace restricted': 'مساحة العمل مقيّدة',
    'Organization verified and workspace active. Actions remain subject to backend/RLS enforcement.': 'المنظمة موثقة ومساحة العمل نشطة. وتظل الإجراءات خاضعة لقواعد backend/RLS.',
    'Business services remain limited until identity and workspace satisfy server-side requirements.': 'تظل خدمات الأعمال محدودة إلى أن تستوفي الهوية ومساحة العمل متطلبات الخادم.',
    'Organization identity, roles, workspace status and permissions are verified server-side. The pilot does not sell verification, ranking or visibility. Verified Results remain separate from ordinary publishing.': 'يتم التحقق من هوية المنظمة والأدوار وحالة مساحة العمل والصلاحيات على الخادم. ولا تبيع التجربة التحقق أو الترتيب أو الظهور. وتظل النتائج الموثقة منفصلة عن النشر العادي.',
    'Run a consultation with QR, Stage, access control and Verified Result.': 'أجرِ استشارة مع QR ومنصة وتحكم في الوصول ونتيجة موثقة.',
    'QR, Stage and Verified Result.': 'QR ومنصة ونتيجة موثقة.',
    'Create Session': 'إنشاء جلسة',
    'Workspace not active': 'مساحة العمل غير نشطة',
    'Workspace Pilot': 'مساحة عمل تجريبية',
    'Workspace active': 'مساحة العمل نشطة',
    'Workspace suspended': 'مساحة العمل معلّقة',
    'Workspace expired': 'انتهت صلاحية مساحة العمل',
    'Owner': 'المالك',
    'Manager': 'المدير',
    'Operator': 'المشغّل',
    'Viewer': 'المشاهد',
  },
  'ro': <String, String>{
    'Roles, additions, changes and revocations are enforced server-side and recorded in the Organization audit.': 'Rolurile, adăugările, modificările și revocările sunt aplicate pe server și înregistrate în jurnalul de audit al organizației.',
    'No active memberships are currently available for this Organization.': 'În prezent nu există apartenențe active pentru această organizație.',
    'Business Pilot': 'Pilot profesional',
    'Official publishing, live consultations and verifiable results in one workspace.': 'Publicare oficială, consultări live și rezultate verificabile într-un singur spațiu de lucru.',
    'Live sessions': 'Sesiuni live',
    'Verified Results': 'Rezultate verificate',
    'No sessions yet': 'Nu există încă sesiuni',
    'Create a session to start collecting participation and results.': 'Creează o sesiune pentru a începe colectarea participării și a rezultatelor.',
    'Voce to communicate, Vote to consult, Session for live participation and verifiable results.': 'Voce pentru comunicare, Vote pentru consultare și o sesiune pentru participare live și rezultate verificabile.',
    'Manage access, QR, questions, stage, participation and session closure.': 'Gestionează accesul, QR, întrebările, scena, participarea și închiderea sesiunii.',
    'New session': 'Sesiune nouă',
    'No sessions': 'Nu există sesiuni',
    'Sessions created by the organization will appear here.': 'Sesiunile create de organizație vor apărea aici.',
    'No Verified Results yet': 'Nu există încă rezultate verificate',
    'When a session closes with a verified report, the result will appear here.': 'Când o sesiune se încheie cu un raport verificat, rezultatul va apărea aici.',
    'Operate sessions': 'Gestionează sesiunile',
    'Team and roles': 'Echipă și roluri',
    'Team unavailable': 'Echipa nu este disponibilă',
    'This version manages already registered Social Vote accounts. External email invitations, link acceptance and Owner transfer remain unavailable until that workflow is complete.': 'Această versiune gestionează conturi Social Vote deja înregistrate. Invitațiile externe prin e-mail, acceptarea prin link și transferul proprietarului rămân indisponibile până la finalizarea acestui flux.',
    'Official organization data powers the public signature, workspace and Business services.': 'Datele oficiale ale organizației alimentează semnătura publică, spațiul de lucru și serviciile profesionale.',
    'Workspace operational': 'Spațiu de lucru operațional',
    'Workspace restricted': 'Spațiu de lucru restricționat',
    'Organization verified and workspace active. Actions remain subject to backend/RLS enforcement.': 'Organizație verificată și spațiu de lucru activ. Acțiunile rămân supuse regulilor backend/RLS.',
    'Business services remain limited until identity and workspace satisfy server-side requirements.': 'Serviciile profesionale rămân limitate până când identitatea și spațiul de lucru îndeplinesc cerințele serverului.',
    'Organization identity, roles, workspace status and permissions are verified server-side. The pilot does not sell verification, ranking or visibility. Verified Results remain separate from ordinary publishing.': 'Identitatea organizației, rolurile, starea spațiului de lucru și permisiunile sunt verificate pe server. Pilotul nu vinde verificare, clasare sau vizibilitate. Rezultatele verificate rămân separate de publicarea obișnuită.',
    'Run a consultation with QR, Stage, access control and Verified Result.': 'Desfășoară o consultare cu QR, scenă, control al accesului și rezultat verificat.',
    'QR, Stage and Verified Result.': 'QR, scenă și rezultat verificat.',
    'Create Session': 'Creează sesiune',
    'Workspace not active': 'Spațiu de lucru inactiv',
    'Workspace Pilot': 'Spațiu de lucru pilot',
    'Workspace active': 'Spațiu de lucru activ',
    'Workspace suspended': 'Spațiu de lucru suspendat',
    'Workspace expired': 'Spațiu de lucru expirat',
    'Owner': 'Proprietar',
    'Manager': 'Responsabil',
    'Operator': 'Operator',
    'Viewer': 'Vizualizator',
  },
  'ru': <String, String>{
    'Business Pilot': 'Бизнес-пилот',
    'Official publishing, live consultations and verifiable results in one workspace.': 'Официальные публикации, консультации в реальном времени и проверяемые результаты в одном рабочем пространстве.',
    'Live sessions': 'Сессии в реальном времени',
    'Verified Results': 'Проверенные результаты',
    'No sessions yet': 'Сессий пока нет',
    'Create a session to start collecting participation and results.': 'Создайте сессию, чтобы начать собирать участие и результаты.',
    'Voce to communicate, Vote to consult, Session for live participation and verifiable results.': 'Voce — для коммуникации, Vote — для консультаций, сессия — для участия в реальном времени и проверяемых результатов.',
    'Manage access, QR, questions, stage, participation and session closure.': 'Управляйте доступом, QR, вопросами, сценой, участием и закрытием сессии.',
    'New session': 'Новая сессия',
    'No sessions': 'Нет сессий',
    'Sessions created by the organization will appear here.': 'Сессии, созданные организацией, появятся здесь.',
    'No Verified Results yet': 'Проверенных результатов пока нет',
    'When a session closes with a verified report, the result will appear here.': 'Когда сессия завершится с проверенным отчётом, результат появится здесь.',
    'Operate sessions': 'Управлять сессиями',
    'Team and roles': 'Команда и роли',
    'Team unavailable': 'Команда недоступна',
    'This version manages already registered Social Vote accounts. External email invitations, link acceptance and Owner transfer remain unavailable until that workflow is complete.': 'Эта версия управляет уже зарегистрированными аккаунтами Social Vote. Внешние приглашения по email, принятие ссылок и передача владельца остаются недоступными до завершения соответствующего процесса.',
    'Official organization data powers the public signature, workspace and Business services.': 'Официальные данные организации используются для публичной подписи, рабочего пространства и бизнес-сервисов.',
    'Workspace operational': 'Рабочее пространство работает',
    'Workspace restricted': 'Рабочее пространство ограничено',
    'Organization verified and workspace active. Actions remain subject to backend/RLS enforcement.': 'Организация проверена, рабочее пространство активно. Действия по-прежнему подчиняются серверным правилам backend/RLS.',
    'Business services remain limited until identity and workspace satisfy server-side requirements.': 'Бизнес-сервисы остаются ограниченными, пока идентичность и рабочее пространство не соответствуют серверным требованиям.',
    'Organization identity, roles, workspace status and permissions are verified server-side. The pilot does not sell verification, ranking or visibility. Verified Results remain separate from ordinary publishing.': 'Идентичность организации, роли, статус рабочего пространства и разрешения проверяются на сервере. Пилот не продаёт проверку, ранжирование или видимость. Проверенные результаты остаются отдельно от обычных публикаций.',
    'Run a consultation with QR, Stage, access control and Verified Result.': 'Проводите консультацию с QR, сценой, контролем доступа и проверенным результатом.',
    'QR, Stage and Verified Result.': 'QR, сцена и проверенный результат.',
    'Create Session': 'Создать сессию',
    'Workspace not active': 'Рабочее пространство не активно',
    'Workspace Pilot': 'Пилотное рабочее пространство',
    'Workspace active': 'Рабочее пространство активно',
    'Workspace suspended': 'Рабочее пространство приостановлено',
    'Workspace expired': 'Срок рабочего пространства истёк',
    'Owner': 'Владелец',
    'Manager': 'Менеджер',
    'Operator': 'Оператор',
    'Viewer': 'Наблюдатель',
  },
  'zh': <String, String>{
    'Business Pilot': '商业试点',
    'Official publishing, live consultations and verifiable results in one workspace.': '官方发布、实时咨询和可验证结果集中在一个工作区中。',
    'Live sessions': '实时会议',
    'Verified Results': '已验证结果',
    'No sessions yet': '暂无会议',
    'Create a session to start collecting participation and results.': '创建会议以开始收集参与和结果。',
    'Voce to communicate, Vote to consult, Session for live participation and verifiable results.': 'Voce 用于沟通，Vote 用于咨询，会议用于实时参与和可验证结果。',
    'Manage access, QR, questions, stage, participation and session closure.': '管理访问、QR、问题、舞台、参与和会议关闭。',
    'New session': '新建会议',
    'No sessions': '暂无会议',
    'Sessions created by the organization will appear here.': '组织创建的会议将显示在此处。',
    'No Verified Results yet': '暂无已验证结果',
    'When a session closes with a verified report, the result will appear here.': '当会议以已验证报告关闭后，结果会显示在此处。',
    'Operate sessions': '管理会议',
    'Team and roles': '团队与角色',
    'Team unavailable': '团队不可用',
    'This version manages already registered Social Vote accounts. External email invitations, link acceptance and Owner transfer remain unavailable until that workflow is complete.': '此版本仅管理已注册的 Social Vote 账户。在相关工作流完成前，外部邮件邀请、链接接受和所有者转移仍不可用。',
    'Official organization data powers the public signature, workspace and Business services.': '组织官方数据用于公开署名、工作区和商业服务。',
    'Workspace operational': '工作区正常运行',
    'Workspace restricted': '工作区受限',
    'Organization verified and workspace active. Actions remain subject to backend/RLS enforcement.': '组织已验证，工作区已激活。操作仍受后端/RLS 强制规则约束。',
    'Business services remain limited until identity and workspace satisfy server-side requirements.': '在身份和工作区满足服务端要求前，商业服务仍受限制。',
    'Organization identity, roles, workspace status and permissions are verified server-side. The pilot does not sell verification, ranking or visibility. Verified Results remain separate from ordinary publishing.': '组织身份、角色、工作区状态和权限由服务端验证。试点不出售验证、排序或曝光。已验证结果与普通发布保持分离。',
    'Run a consultation with QR, Stage, access control and Verified Result.': '运行带 QR、舞台、访问控制和已验证结果的咨询。',
    'QR, Stage and Verified Result.': 'QR、舞台和已验证结果。',
    'Create Session': '创建会议',
    'Workspace not active': '工作区未激活',
    'Workspace Pilot': '工作区试点',
    'Workspace active': '工作区已激活',
    'Workspace suspended': '工作区已暂停',
    'Workspace expired': '工作区已过期',
    'Owner': '所有者',
    'Manager': '管理员',
    'Operator': '操作员',
    'Viewer': '查看者',
  },
};
